### ISSUE TITLE
Docker environment variable for max upload size?

### ISSUE THREAD

**Issue by mindfuucker** [proofrock/pupcloud#10]
Increasing the maximum upload size in Docker is quite cumbersome at the moment as my docker-compose.yml file shows:
```
version: "3"
services:
  pupcloud:
    image: germanorizzo/pupcloud:latest
    user: 1003:1003
    ports:
      - "17178:17178"
    restart: unless-stopped
    entrypoint: ["/pupcloud", "-r", "/data", "--max-upload-size", "1000"]
    environment:
      PID: 1003
      PGID: 1003  
    volumes:
      - /home/user/music:/data
```
If you know how entry points work it quite doable but I suspect users would want an easier method. Or just having documentation about the entrypoint with an example might be sufficient for the moment.
