### ISSUE TITLE
Possible Docker/Pupcloud/External data store gremlin

### ISSUE THREAD

**Issue by DarrenPIngram** [proofrock/pupcloud#45]
**Note, I do not know where the possible problem may lie, but I can report it and if you have ideas what to check to isolate "who has the problem" I am happy to check.**

Environment: Debian 11 server running Docker. Rclone mount (via systemd) used as datastore. Pupcloud ran as a container within. Data directory for Pupcloud is set to access this share.

```
version: '3.3'
services:
    pupcloud:
        restart: unless-stopped
        container_name: pupcloud
        ports:
            - '8080:17178'
        volumes:
            - '/mnt/disks/DB0-UNION:/data'
        environment:
            - PID=1001
            - PGID=1001
            - PUP_TITLE=The Archive
            - PUP_PASSWORD=downundertv
        image: 'germanorizzo/pupcloud:latest'
```

Pupcloud can run (in tests) and serve files. Eventually and silently it stops. You don't get an error (that I can see) and the web app continues to run, but no data is served up or shown.

`docker start pupcloud restarts` things, no errors are shown on restart, and the web app then (after page refresh) will deliver goodies again.

Other info:
```
rclone --version
rclone v1.58.1
- os/version: debian 11.3 (64 bit)
- os/kernel: 5.10.0-13-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.9
- go/linking: static
- go/tags: none
```
-
